### ISSUE TITLE
Generate docker container image on push to master

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/gitgram#28]
After somebody push a commit to master, the CI would run. After that succeeds, a container image should be created. 

Should create two variants:
- alpine
- bullseye (or latest Debian)

For each variant, should create multiple tags:
- latest (synonymous with latest-bullseye)
- latest-alpine
- Git SHA commit

**Comment by PranjalAgni** [comment]
Where do we need to push these docker images?

**Comment by aldy505** [comment]
> Where do we need to push these docker images?

Github container registry

**Comment by PranjalAgni** [comment]
Please assign it to me, would like to work on this

**Comment by aldy505** [comment]
No need to put assignees to the issue, every reader knows you're working on this one if you are saying it. Go ahead! 😃

**Comment by PranjalAgni** [comment]
Hi @aldy505 currently in the `Dockerfile` we are using NodeJS bullseye image, do we need to create one more `Dockerfile` with NodeJS alpine base image?

**Comment by aldy505** [comment]
Create a new Dockerfile.alpine that uses Alpine would be great. Keep the Debian version.

**Comment by aldy505** [comment]
Hi, @PranjalAgni are you currently working on this issue? If you're not, I'm going to take over this.

**Comment by PranjalAgni** [comment]
Sorry I was reading up on it and exploring how we can create/publish docker images from Github actions. Now I have bit of idea, will try to implement this and raise a PR
